# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
# Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.

import random

def user_input():

    # Below 4 lines generate a random 4 digit number where the digits don't repeat and finally converts it into a list
    rand_number = 0
    while len(set(str(rand_number))) != 4:
        rand_number = str(random.randint(1111, 9999))
    rand_number_list = list(rand_number)

    print('Welcome to the Cows and Bulls Game!')
    
    tries = 0

    while True:

        user_number = input('Enter a number: ')
        user_number_list = list(user_number)
        user_number_set = set(user_number_list)
        
        if len(user_number_set) < 4 or len(user_number_set) > 4:
            print('Invalid value. Please enter 4 different digits.')
            continue
    
        tries += 1

        guessed = []

        for x in range(4):
            if user_number_list[x] in rand_number_list and user_number_list[x] != rand_number_list[x]:
                guessed.append('bulls')
            elif user_number_list[x] == rand_number_list[x]:
                guessed.append('cows')
        
        bulls = guessed.count('bulls')
        cows = guessed.count('cows')

        if guessed == ['cows', 'cows', 'cows', 'cows']:
            print('You win!')
            print(f'You had {tries} number of tries.')
            break
        else:
            print(f'{cows} cows, {bulls} bulls')
            continue
        
    

        
            
        




    

user_input()